import React from 'react';

export default () => {
    return (
        <div style={{maxWidth:'100%'}}>
            <h2 style={{paddingTop:'3em', paddingLeft:'3em', paddingBottom:'1em'}}>TÉRMINOS Y CONDICIONES DE USO DE LA APLICACIÓN CONFIRMAPP</h2>
            <p ><a style={{fontWeight:'bold'}}>CONFIRMAPP</a> informa a todas las personas que ingresen o hagan uso de la aplicación (en adelante EL USUARIO) que, previo al acceso a la misma deberán aceptar los presentes “Términos y condiciones de uso”, a través de la modalidad de “aceptación expresa” (marcando la casilla correspondiente para manifestar su aceptación), o de la modalidad de “aceptación por acto inequívoco” (suministrando voluntariamente los datos personales requeridos en el “Formulario de registro”). Lo invitamos a que lea detalladamente los “Términos y condiciones de uso” que se exponen a continuación, y que en el evento en que después de una lectura atenta de los mismos su decisión sea la de no aceptarlos, se abstenga de utilizar la aplicación y los servicios que esta presta. Los presentes “Términos y condiciones de uso” tendrán vigencia a partir del 01 de Enero de 2.020, y se regirán por las siguientes clausulas:</p>
            <p ><a style={{fontWeight:'bold'}}>PRIMERA. DEFINICIONES.</a> Para los fines de los presentes “Términos y condiciones de uso”, las expresiones que a continuación se mencionan, tendrán el siguiente significado:
            <p ><a style={{fontWeight:'bold'}}>1. Confirmapp</a> (En adelante CONFIRMAPP) Es una aplicación móvil (desarrollo tecnológico para móviles con sistemas operativos Android y IOS), que permite a EL USUARIO la planeación estratégica, ya sea de forma individual o grupal, de “Los eventos” a través de la creación de grupos de chats por tiempo limitado que usan una interfaz sencilla, práctica y de muy fácil uso, en la que íconos emoticonos sirven como apoyo para identificar el estado de “Los eventos” y “Las actividades”. </p>
            <p ><a style={{fontWeight:'bold'}}> 2. Formulario de registro</a> Se trata del formulario dispuesto por CONFIRMAPP en la interfaz inicial, para el suministro de datos personales por parte de la persona interesada en hacer uso de la aplicación, con el fin de dar inicio a su proceso de registro como EL USUARIO.  </p>
            <p ><a style={{fontWeight:'bold'}}> 3. El usuario.</a> (En adelante EL USUARIO) Es toda persona que ingresa o tiene la intención de hacer uso de la aplicación, y que para tal fin realiza el proceso de registro descrito en la cláusula CUARTA de los presentes “Términos y condiciones de uso”.  (EL USARIO junto con CONFIRMAPP se denominarán conjuntamente como “las parte”).  </p>
            <p ><a style={{fontWeight:'bold'}}>4. El operador.</a> La aplicación es operada por  WENJAN S.A.S. (en adelante EL OPERADOR), sociedad constituida bajo el ordenamiento jurídico colombiano, identificada con el Número de Identificación Tributaria (NIT) 900.012.214-6, debidamente registrada ante la Cámara de Comercio de Barranquilla. </p>
            <p ><a style={{fontWeight:'bold'}}>5. Los participantes. </a>  Es toda persona que por invitación de EL USUARIO hace parte de forma grupal en la planeación estratégica de “Los eventos”, y por tanto, tiene acceso a las funcionalidades de CONFIRMAPP, incluyendo la participación en un chat grupal por tiempo limitado, y la posibilidad de ser destinatarios de las notificaciones de la aplicación, en el evento en que EL USUARIO así lo determine.  </p>
            <p ><a style={{fontWeight:'bold'}}>6. Los eventos.</a> Cualquier tipo de citas, reuniones, comidas, en general cualquier evento social, que sea programado a través de CONFIRMAPP.</p>
            <p ><a style={{fontWeight:'bold'}}>7. Las actividades.</a> Cualquier paso previo y preparatorio de “Los eventos”, programado por EL USUARIO con “Los participantes”.</p>
            <p ><a style={{fontWeight:'bold'}}>8. Los contenidos. </a> Son todo texto, información, datos, fotografías, gráficos, imágenes, ilustraciones, dibujos, diseños, código HTML, código fuente y código objeto, marcas, logotipos, slogans, signos distintivos, información y descripción de productos, material audiovisual, y cualquier otra información disponible a través de CONFIRMAPP. Todos “Los contenidos” mencionados son propiedad de EL OPERADOR de conformidad con lo establecido en la cláusula OCTAVA.</p>
            <p ><a style={{fontWeight:'bold'}}>9. La información. </a> Son los datos propios y de “Los participantes”, proporcionados por EL USUARIO con el fin de alimentar la aplicación, dentro del marco de lo establecido en la cláusula DÉCIMA SÉPTIMA. </p>
            <p ><a style={{fontWeight:'bold'}}>10. Los terceros. </a> Son aquellos prestadores de servicio de telefonía inalámbrica de EL USUARIO y “Los participantes”, los fabricantes y vendedores de los dispositivos móviles en los que EL USUARIO y “Los participantes” descarguen, instalen, utilicen o accedan a CONFIRMAPP, los creadores del sistema operativo para los dispositivos móviles y el operador de cualquier tienda de aplicaciones o servicios similares mediante los cuales LOS USUARIOS obtengan CONFIRMAPP, los cuales no son parte de los presentes “Términos y condiciones de uso”, no son propietarios ni responsables de CONFIRMAPP, y les aplican las disposiciones descritas en la cláusula DÉCIMA SEXTA.</p>
            <p ><a style={{fontWeight:'bold'}}>SEGUNDA. OBJETO DE CONFIRMAPP.</a> </p>
            <p ><a style={{fontWeight:'bold'}}></a>Una vez EL USUARIO haya realizado correctamente el proceso de registro establecido en la cláusula CUARTA, podrá acceder a los siguientes servicios prestados por EL OPERADOR a través de la aplicación:</p>
            <p ><a style={{fontWeight:'bold'}}>1.</a> Planeación estratégica a título individual o de grupo de “Los eventos”; </p>
            <p ><a style={{fontWeight:'bold'}}>2.</a> Envío de invitaciones a “Los participantes” y organización de los mismos, con el fin de hacer parte de un grupo de chat por tiempo limitado;</p>
            <p ><a style={{fontWeight:'bold'}}>3.</a> Organización y puesta a disposición de EL USUARIO de la información de los contactos de teléfono móvil de “Los participantes”, proporcionada con el fin de que éste pueda administrarla dentro del marco de la organización de “Los eventos”;</p>
            <p ><a style={{fontWeight:'bold'}}>4.</a> Organización del cronograma de “Las actividades” que hacen parte de “Los eventos”, permitiendo a EL USUARIO planificarlas, clasificarlas para su administración, informar a “Los participantes” de la actividad próxima, y enviar notificaciones previas a “Los participantes” a tipo de recordatorio de “Las actividades”, en el evento en que así lo requiera EL USUARIO;</p>
            <p ><a style={{fontWeight:'bold'}}>5.</a> Planificación de viajes para “Los participantes” con conectividad con herramientas como calendarios Outlook, Google calendar, entre otros;</p>
            <p ><a style={{fontWeight:'bold'}}>6.</a> Envío de notificaciones (en el evento en que así lo elija EL USUARIO) relacionadas con el (los) lugar(es) en los que se llevarán a cabo “Las actividades” y/o “Los eventos” a título de recordatorio de las mismas;</p>
            <p ><a style={{fontWeight:'bold'}}>Parágrafo.</a>  CONFIRMAPP se reserva el derecho de adicionar, modificar, o eliminar las funcionalidades de la aplicación en cualquier momento, caso en el cual bastará con que se publique al actualización, sin que medie notificación alguna por parte de EL OPERADOR a EL USUARIO. </p>
            <p ><a style={{fontWeight:'bold'}}>TERCERA. REQUISITOS PARA EL USO DE CONFIRMAPP</a> </p>
            <p ><a style={{fontWeight:'bold'}}></a> EL USUARIO deberá contar con un dispositivo móvil inteligente (Smartphone) o Tableta con sistema operativo Android o IOS, cualquiera de estos con acceso a internet, seguro y confiable. EL OPERADOR, no será responsable por la seguridad de los equipos Smartphone utilizados para el acceso al canal, ni por la disponibilidad del servicio en los dispositivos en los cuales se descargue la aplicación. En la forma permitida por la ley, “Los Contenidos” de CONFIRMAPP son suministrados por EL OPERADOR sin garantía de ningún género, expresa o implícita, en consecuencia, EL OPERADOR no garantiza el funcionamiento adecuado en los distintos sistemas operativos o dispositivos en los cuales se haga uso de la aplicación.</p>
            <p ><a style={{fontWeight:'bold'}}>CUARTA. PROCESO DE REGISTRO</a> <br/> El acceso a la aplicación requiere del registro previo de EL USUARIO, el cual comprende los siguientes pasos:</p>
            <p ><a style={{fontWeight:'bold'}}>1.</a> Esta etapa del proceso puede llevarse a cabo a través de la cuenta de EL USUARIO en la red social Facebook (u otras aplicaciones que no son de propiedad de EL OPERADOR), o a través del diligenciamiento del “Formulario de registro” dispuesto por CONFIRMAPP en la interfaz inicial, el cual requiere del suministro voluntario de datos personales tales como: nombre y apellidos completos, correo electrónico y teléfono de EL USUARIO, entre otros.</p>
            <p ><a style={{fontWeight:'bold'}}>2. Elección de datos de acceso</a> Durante el proceso de registro EL USUARIO deberá elegir (de acuerdo a sus preferencias) un nombre de usuario y contraseña válidos que le permitan acceder a la aplicación y sus servicios. </p>
            <p ><a style={{fontWeight:'bold'}}>3. Aceptación de los “Términos y condiciones de uso”</a>  Previa a la finalización del proceso de registro, EL USUARIO deberá leer detenidamente los presentes “Términos y condiciones de uso”, y aceptarlos expresamente, marcando la casilla correspondiente, o a través del suministro voluntario de la información solicitada en el “Formulario de registro” dispuesto por CONFIRMAPP para tal fin. </p>
            <p ><a style={{fontWeight:'bold'}}>4. Confirmación del registro</a> Una vez surtidos los pasos previamente descritos EL USUARIO recibirá un correo electrónico a través del cual CONFIRMAPP validará su registro como usuario de la aplicación. En este orden de ideas, resulta necesario que el correo electrónico que suministre EL USUARIO en el paso 1 antes descrito, se encuentre activa y operativa.  </p>
            <p ><a style={{fontWeight:'bold'}}>Parágrafo</a> El uso de CONFIRMAPP no tiene restricciones de edad, en el caso de que EL USUARIO o “Los participantes” sean menores de edad, CONFIRMAPP requiere el acompañamiento y la supervisión permanente de un adulto en todas las etapas de uso de la aplicación, las cuales incluyen: la descarga, la manifestación de su aceptación de los “Términos y condiciones de uso”, y el uso de la aplicación. En el evento en que no se cumpla esta condición, deberá cesar el uso de la misma por parte del menor de edad. Así mismo, y en consideración a la naturaleza sensible de los datos personales de niños, niñas y adolescentes, el ejercicio del derecho de habeas data, en lo relativo a la rectificación, actualización o supresión de los mismos, deberá ser realizada por las personas que estén facultadas para representarlos, calidad que debe ser acreditada ante CONFIRMAPP.</p>
            <p ><a style={{fontWeight:'bold'}}>QUINTA. OBLIGACIONES DE EL OPERADOR. </a> <br/> En virtud de los presentes “Términos y condiciones de uso” de la aplicación, EL OPERADOR se compromete a: (i) proteger “La información” con la que EL USUARIO y “Los participantes” alimentan la aplicación; (ii) permitir a EL USUARIO y a “Los participantes”, el acceso a CONFIRMAPP y a sus funcionalidades; (iii) garantizar que es el único titular de los derechos sobre CONFIRMAPP y que por tanto está facultado para otorgar acceso al mismo a EL USUARIO y a “Los participantes” para el uso la aplicación y sus funcionalidades.</p>
            <p ><a style={{fontWeight:'bold'}}>SEXTA. OBLIGACIONES DE EL USUARIO. </a> <br/> Con la aceptación de los presentes “Términos y condiciones de uso” de CONFIRMAPP, EL USUARIO se compromete a:</p>
           <br/>
            <p style={{paddingTop:'0.5em'}}><a style={{fontWeight:'bold'}}></a> Leer, comprender a cabalidad, y aceptar cada una de las disposiciones de los presentes “Términos y condiciones de uso”;</p>
            <p ><a style={{fontWeight:'bold'}}>1.</a> Leer, comprender a cabalidad, y aceptar cada una de las disposiciones de los presentes “Términos y condiciones de uso”;</p>
            <p ><a style={{fontWeight:'bold'}}>2.</a> Establecer, mantener y poner en funcionamiento su conexión con CONFIRMAPP a través de Internet (la velocidad del cual puede tener un impacto significativo en la capacidad de respuesta de la aplicación);</p>
            <p ><a style={{fontWeight:'bold'}}>3.</a> Cumplir con los requerimientos para el uso de la aplicación establecidos en la cláusula TERCERA de los presentes “Términos y condiciones de uso”;</p>
            <p ><a style={{fontWeight:'bold'}}>4.</a> Controlar las invitaciones a “Los Participantes” para el uso de las funcionalidades de la aplicación;</p>
            <p ><a style={{fontWeight:'bold'}}>5.</a> Controlar el acceso no autorizado a CONFIRMAPP con su nombre de usuario y contraseña, y a mantener la confidencialidad de los mismos;</p>
            <p ><a style={{fontWeight:'bold'}}>6.</a> Notificar a EL OPERADOR de inmediato, acerca de cualquier uso no autorizado de los datos de acceso a la aplicación, y a emplear todos los esfuerzos razonables para evitar que terceros no autorizados accedan a CONFIRMAPP;</p>
            <p ><a style={{fontWeight:'bold'}}>7.</a> Garantizar la exactitud, calidad, integridad, legalidad, confiabilidad, adecuación y propiedad de la totalidad de “La información” con la que EL USUARIO y “Los participantes” alimentan la aplicación;</p>
            <p ><a style={{fontWeight:'bold'}}>8.</a> Atender y hacer cumplir la política de uso aceptable de CONFIRMAPP de conformidad con lo establecido en la cláusula DÉCIMA CUARTA;</p>
            <p ><a style={{fontWeight:'bold'}}>9.</a> Así mismo, EL USUARIO reconoce que, al acceder a esta aplicación en Colombia o desde fuera del territorio nacional, se hace responsable del cumplimiento de las leyes locales.</p>
            <p ><a style={{fontWeight:'bold'}}>SÉPTIMA. PROHIBICIONES PARA EL USUARIO RESPECTO A “LOS CONTENIDOS”. </a> </p>
            <p ><a style={{fontWeight:'bold'}}></a> EL USUARIO se obliga a utilizar la aplicación y “Los contenidos” de una manera diligente, correcta, lícita, y en especial, y se compromete a NO realizar las conductas descritas a continuación:</p>
            <p ><a style={{fontWeight:'bold'}}>1.</a> Utilizar “Los contenidos” de forma, con fines o efectos contrarios a la ley, a la moral y a las buenas costumbres o al orden público;</p>
            <p ><a style={{fontWeight:'bold'}}>2.</a> Reproducir, copiar, representar, utilizar, distribuir, transformar o modificar “Los contenidos” de la aplicación, por cualquier procedimiento o sobre cualquier soporte, total o parcial, o permitir el acceso del público a través de cualquier modalidad de comunicación pública;</p>
            <p ><a style={{fontWeight:'bold'}}>3.</a> Utilizar “Los contenidos” de cualquier manera que entrañen un riesgo de daño, inutilización de la aplicación o de los contenidos o de terceros;</p>
            <p ><a style={{fontWeight:'bold'}}>4.</a> Suprimir, eludir o manipular el derecho de autor y demás datos identificativos de los derechos de autor incorporados a “Los contenidos”, así como los dispositivos técnicos de protección, o cualesquiera mecanismos de información que pudieren tener los mismos;</p>
            <p ><a style={{fontWeight:'bold'}}>5.</a> Emplear “Los contenidos” y, en particular, la información de cualquier clase obtenida a través de CONFIRMAPP para distribuir, transmitir, remitir, modificar, reportar la publicidad o “Los contenidos” de ésta con fines de venta directa o con cualquier otra clase de finalidad comercial, mensajes no solicitados dirigidos a una pluralidad de personas con independencia de su finalidad, así como comercializar o divulgar de cualquier modo dicha información;</p>
            <p ><a style={{fontWeight:'bold'}}>6.</a> Permitir que terceros ajenos a EL USUARIO usen CONFIRMAPP con su clave;</p>
            <p ><a style={{fontWeight:'bold'}}>7.</a> Utilizar CONFIRMAPP y “Los contenidos” con fines lícitos y/o ilícitos, contrarios a lo establecido en los presentes “Términos y condiciones de uso”, o al uso mismo de CONFIRMAPP, que sean lesivos de los derechos e intereses de EL OPERADOR o de terceros, o que de cualquier forma puedan dañar, inutilizar, sobrecargar o deteriorar la aplicación y los contenidos o impedir la normal utilización o disfrute de esta y de los contenidos por parte de los usuarios;</p>
            <p ><a style={{fontWeight:'bold'}}>8.</a> Intentar obtener “Los contenidos” de CONFIRMAPP por cualquier medio distinto de los que se pongan a disposición de LOS USUARIOS, que pudiera causarle algún perjuicio a EL OPERADOR;</p>
            <p ><a style={{fontWeight:'bold'}}>9.</a> Usar de cualquier forma contenidos que puedan ser considerados como incultos y/o inmorales, incluidas imágenes y fotografías obscenas. </p>
            <p ><a style={{fontWeight:'bold'}}>OCTAVA. PROPIEDAD INTELECTUAL.</a> </p>
            <p ><a style={{fontWeight:'bold'}}></a> La propiedad de CONFIRMAP, de los servicios que se prestan a través de la aplicación, y de “Los contenidos”, se encuentra protegidos por los derechos de propiedad intelectual que resulten aplicables de acuerdo a su naturaleza, y son de propiedad exclusiva de EL OPERADOR, de sus compañías filiales, vinculadas o subsidiarias, y en algunos casos, de terceros que han autorizado su uso o explotación. Por lo tanto, al visitar, usar o navegar por CONFIRMAPP, EL USUARIO se obliga a respetar y no infringir los derechos de propiedad intelectual sobre “Los contenidos”, ni a reproducir o hacer uso de los mismos sin la autorización previa y por escrito de EL OPERADOR, quien se reserva todos los derechos no expresamente concedidos a EL USUARIO a través de los presentes “Términos y condiciones de uso”.</p>
            <p ><a style={{fontWeight:'bold'}}>1. Marcas</a> CONFIRMAPP y cualquier otra marca de propiedad de EL OPERADOR que identifique cualquiera de los productos en la aplicación, son marcas registradas por éste o por cualquiera de sus empresas filiales o subsidiarias, y por ello, queda prohibida su reproducción, uso o explotación, sin el consentimiento previo, expreso y por escrito por parte de EL OPERADOR. Esta prohibición se extiende a los lemas comerciales y demás signos distintivos que identifican a cada uno de nuestros productos o servicios.</p>
            <p ><a style={{fontWeight:'bold'}}>2. Derechos de autor</a>  EL OPERADOR se reserva todos los derechos de autor sobre “Los contenidos”, textos, fotografías, software, sonidos, videos y material en general, exhibidos en la aplicación, los cuales tienen la calidad de obras protegidas de acuerdo con las leyes colombianas sobre derechos de autor, la Decisión 344 de la Comisión de la Comunidad Andina, y demás disposiciones internacionales aplicables a la materia. Se prohíbe totalmente la comercialización, transferencia, distribución, reproducción, publicación, transmisión, copia, edición, traducción, compilación, almacenamiento, comunicación pública, puesta a disposición, representación, creación de obras derivadas, adaptación, exhibición, procesos de ingeniería inversa, o cualquier otro acto de explotación que recaiga total o parcialmente sobre el contenido, software u obras en general puestas a disposición de EL USUARIO de la aplicación, sin que medie el consentimiento previo, expreso y por escrito de parte de EL OPERADOR.</p>
            <p ><a style={{fontWeight:'bold'}}>3. Contribuciones</a> Las ideas y conceptos expresados a través de las opiniones, sugerencias o comentarios que EL USUARIO envíe de manera espontánea o sin previa solicitud, podrán ser tenidos en cuenta por EL OPERADOR, si así lo estimase conveniente, para el desarrollo o mejoramiento de sus productos, la estructuración de estrategias, planes de mercadeo y campañas publicitarias, bajo el entendimiento de que el aprovechamiento se limitará a la implementación de las ideas o conceptos, y no a la manera en que las contribuciones fueron expresadas por EL USUARIO. En consecuencia, EL USUARIO no tendrá el derecho a recibir pago alguno por el legítimo uso que EL OPERADOR haga de la información suministrada en las condiciones antes descritas.</p>
            <p ><a style={{fontWeight:'bold'}}>Parágrafo</a> En el evento en que EL USUARIO incumpla o vulnere comprobadamente la propiedad intelectual de CONFIRMAPP o de un tercero mediante la retransmisión o publicación de material vinculado con CONFIRMAPP que infrinja los derechos de autor u otros derechos legales de dicho tercero, CONFIRMAPP podrá negar el acceso de EL USUARIO a la aplicación y dar por terminada la prestación de servicios a través de la misma.</p>
            <p ><a style={{fontWeight:'bold'}}>NOVENA. DISPONIBILIDAD Y CONTINUIDAD DEL SERVICIO DE CONFIRMAPP. </a> </p>
            <p ><a style={{fontWeight:'bold'}}></a> CONFIRMAPP fue creada para la versión más reciente y disponible en el mercado de los sistemas operativos de los dispositivos móviles de EL USUARIO, en consecuencia, pueden surgir inconvenientes de compatibilidad cuando se utilicen versiones anteriores. Así mismo, EL OPERADOR no garantiza que el acceso a CONFIRMAPP sea permanente o libre de errores, interrupciones, demoras en la operación, fallas en la transmisión de datos o las conexiones de línea, o que la navegación será libre de virus y demás componentes dañinos. Por tanto, todo uso que LOS USUARIOS hagan de la aplicación será bajo su propia cuenta y riesgo.</p>
            <p style={{paddingTop:'2em'}}><a style={{fontWeight:'bold'}}></a> EL OPERADOR propenderá por mantener la disponibilidad, continuidad y/o buen funcionamiento de CONFIRMAPP, sin embargo, se reserva el derecho a bloquear, interrumpir o restringir el acceso a ésta cuando lo considere necesario para el mejoramiento de la aplicación. Se recomienda a EL USUARIO tomar medidas adecuadas y actuar diligentemente al momento de acceder a la aplicación, como por ejemplo, contar con programas de protección, antivirus, para manejo de malware, spyware y herramientas similares. Tanto “Los contenidos” como los componentes técnicos de CONFIRMAPP pueden incluir errores y fallas técnicas, y por ende, la experiencia de cada USUARIO al navegar por la aplicación podrá variar. Ni EL OPERADOR, sus directivos, propietarios, administradores de contenido, proveedores o licenciatarios (todos colectivamente “Las partes indemnes”) serán responsables de los daños que eventualmente llegaren a sufrir LOS USUARIOS como consecuencia directa o indirecta del acceso, falta de acceso, uso, o falla en el desempeño de CONFIRMAPP. </p>
            <p style={{paddingTop:'2em'}}><a style={{fontWeight:'bold'}}></a> La cobertura de la red inalámbrica y la velocidad de la red de Wi-Fi varían según el proveedor y la ubicación geográfica de EL USARIO, por tal razón, EL OPERADOR no se responsabiliza por: (i) las limitaciones y/o fallas en el funcionamiento de ningún servicio inalámbrico o Wi-FI que se use para acceder a CONFIRMAPP, (ii) por la seguridad de los servicios inalámbricos o Wi-Fi, (iii) los cargos o tarifas por uso de redes de datos, que son exclusiva responsabilidad de EL USUARIO.</p>
            <p ><a style={{fontWeight:'bold'}}> DÉCIMA. FUERZA MAYOR. </a> </p>
            <p ><a style={{fontWeight:'bold'}}></a> EL OPERADOR no será responsable frente a EL USUARIO o frente a terceros por los daños y perjuicios ocasionados, o por las pérdidas que resulten de la demora o imposibilidad de la prestación de los servicios ofrecidos a través de CONFIRMAPP, en el supuesto de que se produzca cualquier circunstancia imprevista o que estando prevista, fuera inevitable al estar fuera de su control. En este orden de ideas, y en lo relativo al uso de los servicios ofrecidos a través de CONFIRMAPP, EL OPERADOR no garantizará que el mismo será siempre seguro, oportuno, ininterrumpido, que carecerá de errores o que funcionará en combinación con cualquier otro hardware, software, sistema o con otros datos, y/o que cumplirá en todo momento los requisitos o expectativas de calidad de EL USUARIO. Sin perjuicio de lo establecido en la presente cláusula, los servicios prestados a través de CONFIRMAPP pueden ser objeto de limitaciones, retrasos y otras incidencias inherentes al uso de Internet. EL OPERADOR no será responsable de los daños derivados por dichas incidencias. </p>
            <p ><a style={{fontWeight:'bold'}}>DÉCIMA PRIMERA. ACTUALIZACIONES DE CONFIRMAPP. </a> </p>
            <p ><a style={{fontWeight:'bold'}}></a> EL OPERADOR se reserva el derecho de efectuar actualizaciones o modificaciones (directa o indirectamente en cualquier forma, en cualquier momento, sin previo aviso y sin requerir autorización de EL USUARIO) de la aplicación, sus procesos y/o sus funcionalidades, y de los servicios que se prestan a través de la misma (que recaigan sobre infraestructura, seguridad, configuraciones técnicas, características de la aplicación, entre otras), incluidas aquellas destinadas a reflejar cambios en la tecnología, prácticas de la industria, pautas de uso, normatividad aplicable y disponibilidad de contenido. Todo lo anterior, con el fin optimizar el funcionamiento de la aplicación y de los servicios que a través de ella se prestan, y de mantener la aplicación actualizada con las mejoras requeridas a nivel técnico, corrección a errores detectados, cambios de ley y mejoras funcionales. En este orden de ideas, EL OPERADOR podrá solicitar a EL USUARIO que actualice su versión de CONFIRMAPP en cualquier momento. Aún cuando EL OPERADOR desplegará todos los esfuerzos con el fin de conservar las configuraciones y preferencias personales de EL USUARIO, no se compromete a conservarlas en los procesos de actualización de la aplicación y los servicios que a través de ella se prestan. </p>
            <p ><a style={{fontWeight:'bold'}}>DÉCIMA SEGUNDA. HIPERVÍNCULOS E INTERACCIÓN CON OTRAS APLICACIONES. </a> </p>
            <p ><a style={{fontWeight:'bold'}}></a> EL OPERADOR selecciona los vínculos (“links”) con los que es posible acceder o ser redirigido a aplicaciones distintas a CONFIRMAPP (incluyendo sin limitarse a Facebook®, Instagram®, twitter®), las cuales pueden incluir o mostrar contenidos que no están bajo el control de EL OPERADOR. Aunque CONFIRMAPP propende el suministro links de sitios y aplicaciones de terceros que cumplan tanto con las leyes y regulaciones aplicables, como con las “Términos y condiciones de uso” establecidas por EL OPERADOR. EL USUARIO acepta que EL OPERADOR no tiene control sobre la naturaleza y el contenido de esos sitios y no está recomendando estos sitios, la información que contienen ni los productos o servicios de terceros. </p>
            <p ><a style={{fontWeight:'bold'}}></a> El acceso y uso de las aplicaciones a las cuales dirigen los “hipervínculos” activados en la aplicación CONFIRMAPP  se encuentran sometidos a términos y condiciones particulares para cada página y que pueden ser distintos a los presentes “Términos y condiciones de uso”. EL USUARIO debe verificar los términos y condiciones, así como la política legal y de privacidad de otras aplicaciones con las cuales se enlaza CONFIRMAPP, razón por la cual el acceso a olas mismas a través de CONFIRMAPP se hará bajo su entero riesgo y responsabilidad. La navegación, interacción y transacciones que EL USUARIO realice en estas aplicaciones, tendrán efectos únicamente entre EL USUARIO y el administrador de las mismas. En este orden de ideas, EL OPERADOR no se hace responsable por:</p>
            <p style={{addingTop:'1em'}}><a style={{fontWeight:'bold'}}>1.</a> El contenido de aplicaciones distintas a CONFIRMAPP que no son de propiedad de EL OPERADOR, con el cual existe un link de hipertexto, y/o a donde dirijan los “hipervínculos” activados en la aplicación;</p>
            <p ><a style={{fontWeight:'bold'}}>2.</a> La garantía (explícita o implícita) en cuanto al contenido de la información en esas aplicaciones, ni por los daños o perjuicios que EL USUARIO pueda llegar a sufrir durante su visita a alguna de ellas;</p>
            <p ><a style={{fontWeight:'bold'}}>3.</a> Pérdidas directas, indirectas o consecuenciales derivadas del uso de aplicaciones distintas a CONFIRMAPP que no son de propiedad de EL OPERADOR;</p>
            <p ><a style={{fontWeight:'bold'}}>4.</a> Examinar o evaluar aspectos técnicos o el contenido suministrado u ofrecido en aplicaciones distintas a CONFIRMAPP que no son de propiedad de EL OPERADOR;</p>
            <p ><a style={{fontWeight:'bold'}}>5.</a> Los bienes y servicios que se comercialicen en aplicaciones distintas a CONFIRMAPP que no son de propiedad de EL OPERADOR, respecto de los cuales EL OPERADOR no asume ninguna obligación.</p>
            <p ><a style={{fontWeight:'bold'}}>Parágrafo</a> Sólo en el evento en que EL OPERADOR haga uso de CONFIRMAPP  como medio de comercio electrónico, dispondrá de un link visible, fácilmente identificable, que permita a EL USUARIO ingresar a la página de la autoridad de protección al consumidor de Colombia</p>
            <p ><a style={{fontWeight:'bold'}}>DÉCIMA TERCERA. LIMITACIÓN DE LA RESPONSABILIDAD DE EL OPERADOR.</a> </p>
            <p > La responsabilidad que para<a style={{fontWeight:'bold'}}>EL OPERADOR</a> se deriva del presente contrato, se limita únicamente a conceder a EL USUARIO el derecho de acceso y uso de la aplicación CONFIRMAPP y de los servicios que a través de la misma se prestan, de conformidad con lo establecido en los presentes “Términos y condiciones de uso”, siempre que EL USUARIO cumpla con todas las estipulaciones contempladas en los mismos, y haya realizado correctamente el proceso de registro establecido en la cláusula CUARTA. EL OPERADOR será responsable del funcionamiento de CONFIRMAPP y de los servicios que se prestan a través de la aplicación, bajo los precisos lineamientos establecidos en los presentes “Términos y condiciones de uso” de la aplicación.</p>
            <p ><a style={{fontWeight:'bold'}}></a>En todo caso, cualquier obligación que se derive para EL OPERADOR de los presentes “Términos y condiciones” será de medio y no de resultado. En consecuencia, a manera enunciativa y no limitativa, EL OPERADOR manifiesta que no será responsable bajo ningún concepto y en ninguna calidad, ni civil, ni administrativa, ni penalmente y que quedará exonerado de toda responsabilidad, por: </p>
            <p ><a style={{fontWeight:'bold'}}>1.</a> El mal uso que EL USUARIO, y “Los participantes” hagan de CONFIRMAPP, así como tampoco por los resultados que arroje el mismo;</p>
            <p ><a style={{fontWeight:'bold'}}>2.</a> Las expectativas de funcionamiento, alcance y/o resultados que EL USUARIO espera de CONFIRMAPP y del uso de la aplicación; </p>
            <p ><a style={{fontWeight:'bold'}}>3.</a> El acceso o la disponibilidad de los servicios de CONFIRMAPP en línea, la operación ininterrumpida o libre de todo error de CONFIRMAPP y los servicios que se prestan a través de la aplicación; </p>
            <p ><a style={{fontWeight:'bold'}}>4.</a> “La información” compartida en, o a través, de CONFIRMAPP por EL USUARIO, “Los participantes” y por terceros, que se encuentre prohibida por la ley, sea contraria al orden público o a las buenas costumbres, o que atente contra los derechos de EL OPERADOR y/o de terceros;</p>
            <p ><a style={{fontWeight:'bold'}}>5.</a> Reclamaciones de autoridades judiciales, administrativas o entes de control nacionales o internacionales y/o de cualquier tercero en contra de EL USUARIO.</p>
            <p ><a style={{fontWeight:'bold'}}>Parágrafo</a> En todo caso, EL OPERADOR no será responsable por la pérdida, extravío o hurto de  dispositivos móviles que permitan el acceso de terceros a la aplicación móvil; por errores en la digitación o accesos por parte de EL USUARIO; por los perjuicios, lucro cesante, daño emergente, morales, y en general sumas a cargo de  EL OPERADOR, que tengan origen en los retrasos, falta de procesamiento de información, o suspensión del servicio del operador móvil o daños en los dispositivos móviles.</p>
            <p ><a style={{fontWeight:'bold'}}>DÉCIMA CUARTA. POLÍTICA DE USO ACEPTABLE DE CONFIRMAPP. </a> EL USUARIO acepta no usar ni permitir el uso de CONFIRMAPP, para cualquier finalidad que:

</p>
            <p style={{addingTop:'1em'}}><a style={{fontWeight:'bold'}}></a> EL USUARIO acepta no usar ni permitir el uso de CONFIRMAPP, para cualquier finalidad que:</p>
            <p ><a style={{fontWeight:'bold'}}>1.</a> Implique una amenaza o acoso a cualquier persona o cause daños o lesiones a personas o bienes;</p>
            <p ><a style={{fontWeight:'bold'}}>2.</a> Implique la publicación de material falso difamatorio, acosador u obsceno; </p>
            <p ><a style={{fontWeight:'bold'}}>3.</a> Viole los derechos de privacidad o promueva la intolerancia, el racismo, el odio o el daño; </p>

            <p ><a style={{fontWeight:'bold'}}>4.</a> Constituya correo electrónico masivo no solicitado, correo “basura” (“junk mail”), correo "no deseado” (“spam”) o mensajes en cadena; </p>
            <p ><a style={{fontWeight:'bold'}}>5.</a> Constituya una violación de derechos de propiedad intelectual, industrial u otros derechos de autor; o </p>
            <p ><a style={{fontWeight:'bold'}}>6.</a> Viole de cualquier forma las leyes. </p>
            <p ><a style={{fontWeight:'bold'}}></a> EL OPERADOR se reserva el derecho, sin por ello ostentar la obligación, de adoptar medidas correctivas si algún material vulnera las restricciones mencionadas en la presente cláusula, incluida la terminación o suspensión de los servicios prestados a través de la aplicación, sin que ello genere el pago de indemnizaciones o compensaciones a favor de EL USUARIO, quien ostenta la responsabilidad exclusiva relacionada con la exactitud, calidad, integridad, legalidad, confiabilidad, adecuación y propiedad de la totalidad de “La información” que ingresa y comparte a través de CONFIRMAPP.  </p>
            <p ><a style={{fontWeight:'bold'}}>DÉCIMA QUINTA. RESPONSABILIDAD DE EL USUARIO. </a> </p>
            <p ><a style={{fontWeight:'bold'}}>“Los participantes.</a> EL USUARIO será responsable de todas las actividades que se realizan con su nombre de usuario y contraseña, o como consecuencia del acceso a CONFIRMAPP por su parte o por parte de cualquier tercero que EL USUARIO haya autorizado para acceder a la aplicación con sus datos de acceso, y acepta notificar a EL OPERADOR de inmediato acerca de cualquier uso no autorizado del que tenga conocimiento. EL USUARIO acuerda emplear todos los esfuerzos razonables para evitar que terceros no autorizados accedan a la aplicación. En consideración a que EL USUARIO será responsable de identificar a “Los participantes” que el invite a acceder a CONFIRMAPP con el fin de efectuar la planeación estratégica o la asistencia a “Los eventos”, se compromete a mantener indemne a EL OPERADOR por cualquier daño causado por “Los participantes”</p>
            <p ><a style={{fontWeight:'bold'}}></a> EL OPERADOR se reserva el derecho, sin por ello ostentar la obligación, de adoptar medidas correctivas, en cualquier momento y sin necesidad de que medie aviso previo), en el evento en que detecte el acceso a CONFIRMAPP de terceros no autorizados que hagan uso del nombre de usuario y la contraseña elegida por EL USUARIO para hacer uso de las funcionalidades de la aplicación, incluida la terminación o suspensión de los servicios prestados a través de la aplicación, sin que ello genere el pago de indemnizaciones o compensaciones a favor de EL USUARIO, quien ostenta la responsabilidad exclusiva relacionada con todas las actividades que se realizan con su nombre de usuario y contraseña,</p>
            <p ><a style={{fontWeight:'bold'}}>DÉCIMA SEXTA. RESPONSABILIDAD DE “LOS TERCEROS”.</a> En consideración a que “Los terceros” y sus empresas subsidiarias, ostentan la calidad de beneficiarios de los presentes “Términos y condiciones de uso”, no se consideran como parte de los mismos, y por tal razón: (i) no se encuentran en la capacidad de garantizar la prestación de los servicios ofrecidos a través de CONFIRMAPP, y por lo tanto no son responsables de la prestación de los mismos; (ii) no son responsables del mantenimiento u otros servicios de soporte técnico de la aplicación; (iii) no son responsables respecto a cualquier otro reclamo, pérdidas, imputación de responsabilidades, daños y perjuicios, costos o gastos vinculados con CONFIRMAPP.</p>
            <p ><a style={{fontWeight:'bold'}}>DÉCIMA SÉPTIMA. INFORMACIÓN DE EL USUARIO. </a> Se deja constancia que dentro del marco del acceso y uso de los servicios ofrecidos por CONFIRMAPP, EL USUARIO alimentará a la aplicación con información propia y de “Los participantes” (“La información”), la cual será accesible individualmente por parte de EL USUARIO y de las personas expresamente autorizadas por éste para tal fin. Dicha información o datos operativos de EL USUARIO, serán de su exclusiva propiedad. En este orden de ideas, EL OPERADOR adquiere las siguientes obligaciones respecto a “La información”: (i) guardar secreto y mantener la más estricta confidencialidad sobre “La información” de propiedad de EL USUARIO, a la que tenga acceso en virtud de su registro, acceso y uso de los servicios prestados a través de CONFIRMAPP; (ii) abstenerse de efectuar actividad alguna sobre “La información” sin la autorización de EL USUARIO, ya se trate de reproducción, uso, conservación, modificación o de cualquier otra índole, para finalidades distintas a la prestación de los servicios a través de CONFIRMAPP; (iii) no permitir, el acceso a “La información” bajo ninguna circunstancia, sin que medie el consentimiento previo y expreso de EL USUARIO, salvo requerimiento judicial, evento en el cual EL OPERADOR le comunicará a EL USUARIO, la existencia de dicho requerimiento.</p>
            <p ><a style={{fontWeight:'bold'}}>DÉCIMA OCTAVA. AUTORIZACIÓN PARA EL TRATAMIENTO DE DATOS PERSONALES.</a> De conformidad con lo dispuesto en la Ley Estatutaria 1581 de 2012, el Decreto Reglamentario 1377 de 2013, y demás normas que regulen, sustituyan o modifiquen el Régimen Nacional de Protección de Datos Personales, en cumplimiento del desarrollo legal del derecho constitucional de Habeas Data, EL USUARIO, quien para los efectos de los presentes “Términos y condiciones de uso” de la aplicación actúa como Titular de la Información, con la aceptación de los mismos otorga su consentimiento previo, expreso, e informado a EL OPERADOR, y/o a sus encargados, de toda información o Datos personales relacionados o que pueden asociarse a EL USUARIO y que éste le revelado a EL OPERADOR al momento de su registro, o durante el acceso y uso de los servicios prestados por CONFIRMAPP, sin importar su naturaleza, ya sean: </p>
            <p ><a style={{fontWeight:'bold'}}>1.</a> Datos de identificación, de ubicación, datos socio económicos, entre otros, los cuales, en cumplimiento del principio de veracidad, sean suministrados de forma completa exacta, actualizada y verificable; o,</p>
            <p ><a style={{fontWeight:'bold'}}>2.</a> Información de carácter sensible, entendida como información cuyo tratamiento pueda afectar su intimidad o generar algún tipo de discriminación, según lo establecido en la normatividad vigente, incluyendo pero sin limitarse a datos biométricos, pertenencia a sindicatos u organizaciones sociales, de derechos humanos o que promuevan intereses de cualquier partido político o que garanticen los derechos y garantías de partidos políticos de oposición, condición socioeconómica, origen racial o étnico, orientación política, convicciones religiosas o filosóficas, así como los datos relativos a la salud y a la vida sexual, entre otros. </p>
            <p ><a style={{fontWeight:'bold'}}></a> Con la aceptación de los presentes “Términos y condiciones de uso” de la aplicación y el suministro voluntario de sus datos personales al diligenciar el “Formulario de registro”, EL USUARIO autoriza a EL OPERADOR, y le permite el tratamiento de sus datos personales y reconoce que los datos suministrados son ciertos, dejando por sentado que no se ha omitido o adulterado toda o parte de la información. Así mismo, EL USUARIO garantiza que ha obtenido la autorización de “Los participantes” en su calidad de terceros, que hayan sido incluidos dentro de los datos por ellos suministrados, como números telefónicos, o cualquier otro dato de un tercero suministrado en virtud de su calidad de usuario de CONFIRMAPP. </p>
            <p ><a style={{fontWeight:'bold'}}>Parágrafo primero.</a>  EL USUARIO manifiesta que ha sido informado de que su consentimiento para autorizar el Tratamiento de sus Datos Sensibles o Información referente a sus hijos menores de edad, es completamente opcional, a menos que exista un deber legal que le exija revelarlos o sea necesario revelarlos con el fin de salvaguardar su interés vital siempre que se encuentre en incapacidad física, jurídica y/o sicológica para hacerlo. Adicionalmente declara que ha sido informado de cuáles son los Datos Sensibles que EL OPERADOR tratará y que ha dado su autorización para ello conforme a lo dispuesto en la legislación vigente. </p>
            <p ><a style={{fontWeight:'bold'}}>Parágrafo segundo. </a> EL USUARIO declara que ha sido informado de que el tratamiento de sus datos personales y datos sensibles se ajustará a la política de tratamiento de datos EL OPERADOR a la cual tiene acceso, conoce y sabe que puede ser consultada en la aplicación, o en su defecto, solicitándola al correo electrónico info@confirmapp.com</p>
            <p ><a style={{fontWeight:'bold'}}>Parágrafo tercero.</a> EL USUARIO declara que, previa a la suscripción del presente contrato, ha sido informado de los derechos de Habeas Data que le asisten como titular de Datos Personales y Datos Sensibles, particularmente, los derechos a conocer, actualizar, rectificar, y suprimir los datos personales o de revocar la autorización aquí otorgada, en los términos y bajo el procedimiento consagrado en la política de tratamiento de datos. Igualmente, señala que ha sido informado de su derecho a solicitar prueba de la autorización otorgada a EL OPERADOR para el tratamiento de sus datos personales y datos sensibles y que es consciente de los alcances jurídicos de dicha autorización.</p>
            <p ><a style={{fontWeight:'bold'}}>DÉCIMA NOVENA. FINALIDADES DEL TRATAMIENTO DE LA INFORMACIÓN. </a> EL OPERADOR le informa a EL USUARIO que, en cumplimiento de su deber legal y reglamentario, y en su calidad de Responsable del Tratamiento de sus datos personales, propende por hacer efectiva la garantía constitucional de protección a la intimidad manteniendo la confidencialidad de los mismos. En ese sentido, el tratamiento de los datos personales que EL OPERADOR recolecte, almacene, administre, utilice, tienen como finalidad: (i) prestar los servicios definidos en la cláusula SEGUNDA: (ii) lograr una eficiente comunicación con EL USUARIO respecto a las funcionalidades de CONFIRMAPP; (iii) facilitar el acceso general de EL USUARIO a la información sobre la aplicación y los servicios que se prestan a través de la misma; (iv) informar a EL USUARIO sobre nuevos servicios o funcionalidades de la aplicación. </p>
            <p ><a style={{fontWeight:'bold'}}>VIGÉSIMA. TERMINACIÓN O SUSPENSIÓN DEL SERVICIO. </a> EL USUARIO tiene la posibilidad de eliminar su registro o desactivar su cuenta en cualquier momento. Por su parte, EL OPERADOR se reserva el derecho a suspender y/o desactivar la cuenta de EL USUARIO como consecuencia de cualquier incumplimiento por parte de este ultimo de los presentes “Términos y condiciones de uso” de la aplicación, caso en el cual EL OPERADOR: (i) Notificará al usuario de la medida implementada respecto de su registro como usuario y/o su cuenta, al correo electrónico proporcionado por EL USUARIO al momento del registro; y (ii) Eliminará toda la información, datos y contenidos suministrados por EL USUARIO al momento del registro, y durante el término en el que hizo uso de CONFIRMAPP. </p>
            <p ><a style={{fontWeight:'bold'}}>VIGÉSIMA PRIMERA. NORMATIVIDAD APLICABLE.</a> La validez, interpretación y ejecución de los presentes “Términos y condiciones de uso” se regirán  por las leyes de la República de Colombia. En consecuencia, EL OPERADOR y EL USUARIO se someten a la jurisdicción exclusiva de los jueces y tribunales de la República de Colombia, en lo que respecta al acceso y uso de los servicios prestados a través de CONFIRMAPP, salvo en lo que respecta a la propiedad industrial y los derechos de autor, asuntos que también se regirán por la normatividad de la Comunidad Andina de Naciones y demás normas supranacionales procedentes.</p>
            <p ><a style={{fontWeight:'bold'}}>VIGÉSIMA SEGUNDA. DIVISIBILIDAD DE LAS DISPOSICIONES.</a> La nulidad, ineficacia o inexigibilidad de alguna de las cláusulas de los “Términos y condiciones de uso” de la aplicación, no afectará la validez, eficacia y exigibilidad de las demás cláusulas. En consecuencia, el resto de disposiciones se mantendrán incólumes frente a la disposición inválida, nula, inexigible o ineficaz, conservando íntegramente su carácter vinculante.</p>
            <p ><a style={{fontWeight:'bold'}}>VIGÉSIMA TERCERA. MODIFICACIONES.</a> EL OPERADOR podrá, cuando lo considere conveniente, efectuar actualizaciones o modificaciones en los presentes “Términos y condiciones de uso”, en cualquier momento, sin previo aviso y sin requerir autorización de EL USUARIO. Para el efecto publicará el texto actualizado de los “Términos y condiciones de uso” en la aplicación, indicando la fecha en que entrarán a regir las nuevas disposiciones y notificará de dicha actualización al usuario a través del sistema de notificaciones de la aplicación.</p>
            <p ><a style={{fontWeight:'bold'}}>VIGÉSIMA CUARTA. NOTIFICACIONES.</a> Cualquier comunicación dirigida a EL OPERADOR deberá ser remitida a la Carrera 57 N° 79-118 en Barranquilla, Colombia; al número telefónico +57 5 3553435; o a la siguiente dirección de correo electrónico info@confirmapp.com</p>
            <p ><a style={{fontWeight:'bold'}}>VIGÉSIMA QUINTA. DECLARACIÓN DE ACEPTACIÓN.</a> Con la aceptación de los presentes “Términos y condiciones de uso” de la aplicación, EL USUARIO manifiesta que ha leído y comprendido a cabalidad cada una de las disposiciones que los componen, que cuenta con el conocimiento integral y consciente de los mismos, que aprueba la totalidad de sus estipulaciones de forma voluntaria e informada, que acepta quedar vinculado de conformidad con el contenido de los mismos, y que hará uso de la aplicación sin contravenir la legislación vigente, la buena fe, los usos honestos, el orden público, la moral y las buenas costumbres. En el evento en que después de una lectura atenta de los mismos su decisión sea la de no aceptarlos, solicitamos abstenerse de utilizar la aplicación y los servicios que esta presta. </p>
            

</p>  
        </div>
    )
}