import React from 'react';

export default () => {
    return (
        <div style={{maxWidth:'100%', paddingRight:'4em'}}>
        <div style={{ paddingLeft:'4em'}}>
            <h2 style={{paddingTop:'3em', paddingLeft:'2em', paddingBottom:'1em'}}>POLÍTICA PARA EL TRATAMIENTO Y PROTECCIÓN EN MATERIA DE DATOS PERSONALES DE LA SOCIEDAD WENJAN S.A.S.</h2>
            <p style={{paddingLeft:'2em',}}><a style={{fontWeight:'bold'}}>WENJAN S.A.S.</a>, Sociedad por Acciones Simplificada, debidamente constituida de acuerdo a las leyes de la República de Colombia (en adelante WENJAN), mediante el presente documento establece sus POLÍTICAS DE TRATAMIENTO Y PROTECCIÓN EN MATERIA DE DATOS PERSONALES, las cuales fundamentan la debida protección, uso y privacidad del derecho de Habeas Data de toda aquella persona jurídica y natural que durante el ejercicio de la actividad económica principal de WENJAN, le suministre Datos Personales por cualquier canal o medio. Las presentes políticas constituyen un acuerdo integral con WENJAN, por consiguiente, se recomienda leer atentamente cada una de las estipulaciones establecidas en las cláusulas que se exponen previas las siguientes consideraciones preliminares, y que pueden ser consultadas o solicitadas en el correo electrónico: info@confirmapp.com </p>
            <br/>
             <h6 style={{fontWeight:'bold'}}>CONSIDERACIONES PRELIMINARES</h6>
             <br/>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>·</a>Que WENJAN, es una Sociedad por Acciones Simplificada (S.A.S), debidamente constituida bajo el ordenamiento jurídico colombiano, identificada con el Número de Identificación Tributaria (NIT) 900.012.214-6, registrada ante la Cámara de Comercio de Barranquilla con la Matrícula Mercantil número 388,385, cuyo domicilio social se encuentra ubicado en la Carrera 57 No. 79-118 en Barranquilla, y con teléfono de contacto (+57) 5 3553435;</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>·</a>Que WENJAN, dentro del marco del desarrollo de sus actividades económicas requiere, recolecta, almacena, usa, hace circular y/o suprime datos de carácter personal correspondientes a personas naturales con quienes tiene o ha tenido relación o vínculo. En consecuencia es el Responsable de organizar los datos de carácter personal respecto de los cuales ejerce Tratamiento, en bases de Datos Personales, con el fin de ejercer un Tratamiento sobre los mismos, al almacenarlos, consultarlos, actualizarlos, compartirlos y/o eliminarlos;</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>·</a>Que en cumplimiento del régimen de protección al derecho de Habeas Data consagrado en los artículos 15 y 20 de la Constitución Política, reglamentado a través de la Ley 1581 de 2.012, el Decreto 1377 de 2.013, el Decreto 886 de 2.014 y el Decreto Único 1074 de 2.015, WENJAN adopta mediante las presentes POLÍTICAS, el manual interno en el cual establece los procedimientos aplicables en virtud de su calidad de Responsable del Tratamiento de Datos Personales de terceros;</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>·</a>Que de acuerdo a lo dispuesto en el artículo 8 de la Ley 1581 de 2.012, mediante las presentes políticas WENJAN otorga los canales necesarios para que las terceras personas en calidad de Titulares de información personal y en reconocimiento de su derecho de Habeas Data, ejerzan sus derechos de conocer, actualizar, rectificar sus Datos Personales, realicen reclamos y consultas, entre otros;</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>·</a>Que la aceptación de las presentes POLÍTICAS constituye condición obligatoria e indispensable para establecer un vínculo con WENJAN, siempre que la configuración de dicho vínculo conlleve al suministro de Datos Personales a la sociedad por cualquier canal o medio durante el ejercicio de sus actividades económicas. En consecuencia, se recomienda que antes de otorgar los datos requeridos por la sociedad, y que serán objeto de Tratamiento por parte de WENJAN, lea atentamente cada una de las disposiciones establecidas en las siguientes,</p>
            <h4 style={{paddingTop:'3em', paddingLeft:'2em', paddingBottom:'1em'}}>CLÁUSULAS</h4>
            <h6 style={{fontWeight:'bold', paddingLeft:'2em', fontSize:'0.9em'}}>CAPÍTULO I. DE LA PROTECCIÓN DE DATOS PERSONALES</h6>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>·</a><a style={{fontWeight:'bold'}}>PRIMERA. Objeto.</a> En cumplimiento de las obligaciones dispuestas por el ordenamiento jurídico colombiano, las presentes políticas de Tratamiento y protección en materia de Datos Personales constituyen el manual interno de <a style={{fontWeight:'bold'}}>WENJAN</a>, mediante el cual determina las políticas y procedimientos a adoptar para la debida protección, uso y reconocimiento de la privacidad del derecho de Habeas Data de todo aquella persona natural que le suministre Datos Personales a la sociedad por cualquier canal o medio durante el ejercicio de su actividad económica principal.</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>SEGUNDA. Definiciones.</a> Para un mayor entendimiento de las disposiciones aquí establecidas, se debe tener en cuenta las definiciones enunciadas a continuación, las cuales se establecen de conformidad con lo establecido en la legislación colombiana vigente:</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>1.</a><a style={{fontWeight:'bold'}}> Autorización:</a> Consentimiento previo, expreso e informado del Titular para llevar a cabo el Tratamiento de Datos Personales;</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>2.</a><a style={{fontWeight:'bold'}}> Aviso de privacidad:</a> Comunicación verbal o escrita generada por el Responsable, dirigida al Titular para el Tratamiento de sus Datos Personales, mediante la cual se le informa acerca de la existencia de las políticas de Tratamiento de información que le serán aplicables, la forma de acceder a las mismas y las finalidades del Tratamiento que se pretende dar a los Datos Personales. Para el caso particular de los usuarios de las aplicaciones operadas por WENJAN, y sin perjuicio de lo establecido en la presente cláusula, el aviso de privacidad estará incluido en la cláusula de los “Términos y condiciones de uso” que regula la “Autorización para el Tratamiento de Datos Personales”.</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>3.</a><a style={{fontWeight:'bold'}}> Base de Datos:</a> Conjunto organizado de Datos Personales que se utiliza para llevar el registro y la administración de los mismos independientemente de la cantidad de Datos Personales que contenga, bien sea en medio físico, como en un archivo físico, o en medio electrónico a través de archivos en cualquier formato como hojas electrónicas, Tratamiento de texto, con el uso o no de motores de bases de datos;</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>4.</a><a style={{fontWeight:'bold'}}> Dato personal:</a>Cualquier información vinculada o que pueda asociarse a una o varias personas naturales determinadas o determinables, tales como:</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1.</a><a style={{fontWeight:'bold'}}></a> Datos de identificación. Aquellos que buscan individualizar a una persona natural, como lo son: el nombre, apellido, tipo de identificación, número de identificación, fecha y lugar de expedición, nombre, estado civil, sexo, firma, nacionalidad, datos de familia, firma electrónica, otros documentos de identificación, lugar y fecha de nacimiento o muerte, edad, huella, ADN, iris, geometría facial o corporal, fotografías, videos, fórmula dactiloscópica, voz, entre otros;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2.</a><a style={{fontWeight:'bold'}}></a> Datos de ubicación. Aquellos relacionados con la actividad comercial o privada de las personas como dirección, teléfono, correo electrónico, entre otros;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3.</a><a style={{fontWeight:'bold'}}></a> Datos de contenido socioeconómico. Aquellos datos de carácter financiero, crediticio y/o de carácter económico de las personas, o relacionados con el factor patrimonial, tales como el otorgamiento de información respecto a la propiedad de bienes muebles e inmuebles, ingresos, egresos, inversiones, historia laboral, experiencia laboral, cargo, fechas de ingreso y retiro, anotaciones, llamados de atención, nivel educativo, capacitación y/o historial académico de la persona, entre otros;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>4.</a><a style={{fontWeight:'bold'}}></a> Datos sensibles. Aquellos relacionados con: (i) El estado de salud de la persona en cuanto a órdenes y relación de pruebas complementarias como laboratorio, imágenes diagnósticas, endoscópicas, patológicas, estudios, diagnósticos médicos, generales o especializados, psicológicos o psiquiátricos, medicamentos y/o Tratamientos médicos o terapéuticos de cualquier tipo; (ii) La pertenencia a sindicatos, organizaciones sociales, de derechos humanos, religiosas, políticas; (iii) Datos relacionados con las convicciones religiosas, filosóficas y/o políticas, los datos de preferencia, identidad y orientación sexual de la persona, origen étnico-racial; (iv) Datos de personas de la tercera edad o menores de 18 años; (v) Datos sobre personas en situación de discapacidad o personas con limitaciones sicomotoras, auditivas y visuales en condiciones de pobreza; (vi) Datos de personas víctimas de la violencia, personas en situación de desplazamiento forzado por violencia, madres gestantes o lactantes o cabeza de familia en situación de vulnerabilidad, menores en condición de abandono o protección, entre otros.</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>5</a><a style={{fontWeight:'bold'}}> Delegado para la protección: </a>de Datos Personales: Persona delegada por el Responsable como encargada de: (i) la vigilancia y la aplicación de la presente Política para el Tratamiento y Protección en Materia de Datos Personales; (ii) el manejo de los Datos Personales, la atención de el Titular de Datos Personales en relación con la protección de los datos; (iii) la recepción y atención de peticiones, quejas, reclamos y consultas de conformidad con la Ley y las presentes políticas; </p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>6</a><a style={{fontWeight:'bold'}}> Encargado: </a> Persona natural o jurídica, pública o privada, que por sí misma o en asocio con otros, realice el Tratamiento de Datos Personales por cuenta del Responsable del Tratamiento. Para efectos de la normativa sobre protección de Datos Personales el Encargado del Tratamiento es un tercero, ajeno a la sociedad, por lo que no debe confundirse con el empleado que al interior de la organización es quien administra la Base de Datos;</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>7</a><a style={{fontWeight:'bold'}}> Responsable: </a> Persona natural o jurídica, pública o privada, que por sí misma o en asocio con otros, decida sobre la Base de Datos y/o el Tratamiento de los datos; </p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>8</a><a style={{fontWeight:'bold'}}> Titular: </a> Persona natural cuyos Datos Personales sean objeto de Tratamiento;</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>9</a><a style={{fontWeight:'bold'}}> Tratamiento:</a> El Tratamiento y la administración de Datos Personales implica su recolección, almacenamiento, consulta, uso, actualización, difusión, transferencia, transmisión, entrega a terceros y/o eliminación, y en general cualquier actividad u operación que se efectúe sobre los Datos Personales del Titular para los fines que decida la empresa;</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>10</a><a style={{fontWeight:'bold'}}> Transferencia:</a> La transferencia de datos tiene lugar cuando el Responsable y/o Encargado del Tratamiento de Datos Personales, ubicado en Colombia, envía la información o los Datos Personales a un receptor, que a su vez es Responsable del Tratamiento y se encuentra dentro o fuera del país; </p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>11</a><a style={{fontWeight:'bold'}}> Transmisión:</a> Tratamiento de Datos Personales que implica la comunicación de los mismos dentro o fuera del territorio de la República de Colombia cuando tenga por objeto la realización de un Tratamiento por el Encargado por cuenta del Responsable.</p>
            <p style={{paddingLeft:'4.5em',}}><a style={{fontWeight:'bold'}}> TERCERA. Principios.</a> WENJAN, en el desarrollo de su objeto social, recolectará, almacenará, usará, transferirá, transmitirá, y en general realizará cualquier actividad u operación -Tratamiento- sobre los Datos Personales. En todo Tratamiento realizado por WENJAN, el Responsable, Encargados y/o terceros a quienes se les transfieran Datos Personales deberán dar cumplimiento a los principios y reglas establecidas en la Ley y en la presente Política, con el fin de garantizar el derecho constitucional que tienen todas las personas a conocer, actualizar y rectificar las informaciones que se hayan recogido sobre ellas en bases de datos o archivos, estos principios son:</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1</a><a style={{fontWeight:'bold'}}> Legalidad en materia de Tratamiento de datos: </a> El Tratamiento a que se refiere la Ley 1581 de 2012 y sus Decretos Reglamentarios 1377 de 2013 y 886 de 2014, es una actividad reglada que debe sujetarse a lo establecido en dichas disposiciones y en las demás que la desarrollen;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2</a><a style={{fontWeight:'bold'}}> Finalidad: </a> El Tratamiento debe obedecer a una finalidad legítima de acuerdo con la Constitución y la Ley, la cual debe ser informada al Titular al momento de obtener su Autorización. Los Datos Personales no podrán ser Tratados por fuera de las finalidades informadas y consentidas por los Titulares;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3</a><a style={{fontWeight:'bold'}}> Libertad:</a> El Tratamiento sólo puede ejercerse con el consentimiento, previo, expreso e informado del Titular -Autorización-. Los Datos Personales no podrán ser obtenidos o divulgados sin previa Autorización, o en ausencia de mandato legal o judicial que releve el consentimiento. Con relación a los Datos Personales obtenidos con anterioridad a la vigencia de la Ley 1581 de 2012, WENJAN utilizará los medios ordinarios y alternativos pertinentes para convocar a el Titular y adelantar el proceso de validación correspondiente, siguiendo lo establecido por el Decreto 1377 de 2013; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>4</a><a style={{fontWeight:'bold'}}> Veracidad o calidad:</a>  La información sujeta a Tratamiento debe ser veraz, completa, exacta, actualizada, comprobable y comprensible. Se prohíbe el Tratamiento de datos parciales, incompletos, fraccionados o que induzcan a error; en este caso WENJAN podrá solicitar al Titular que complete o corrija la información;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>5</a><a style={{fontWeight:'bold'}}> Transparencia: </a> En el Tratamiento debe garantizarse el derecho del Titular a obtener del Responsable del Tratamiento o del Encargado del Tratamiento, en cualquier momento y sin restricciones, información acerca de la existencia de datos que le conciernan. La información será suministrada por el (los) empleado(s) de WENJAN Encargado(s) de la protección de los Datos Personales; la respuesta a la solicitud deberá hacerse por escrito enviado por correo certificado a la dirección suministrada por el Titular, o por el medio informado por el Titular para recibir la respuesta; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>6</a><a style={{fontWeight:'bold'}}> Acceso y circulación restringida:</a> El Tratamiento se sujeta a los límites que se derivan de la naturaleza de los Datos Personales, por la Constitución, las disposiciones de la Ley 1581 de 2012, su Decreto Reglamentario 1377 de 2013. En este sentido, el Tratamiento sólo podrá hacerse por personas autorizadas por el Titular y/o por las personas previstas en la Ley. Los Datos Personales, salvo la información pública, no podrán estar disponibles en Internet u otros medios de divulgación o comunicación masiva, salvo que el acceso sea técnicamente controlable para brindar un conocimiento restringido sólo a los Titulares o terceros autorizados conforme a la Ley 1581 de 2012 y su Decreto Reglamentario 1377 de 2013;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>7</a><a style={{fontWeight:'bold'}}> Temporalidad: </a> WENJAN no usará la información del Titular más allá del plazo razonable que exija la finalidad que fue informada al Titular, y en la medida que el propósito de su Tratamiento lo justifique. Una vez cumplida la o las finalidades del Tratamiento y sin perjuicio de normas legales que dispongan lo contrario, se procederá con la supresión. No obstante lo anterior, los Datos Personales deberán ser conservados cuando así se requiera para el cumplimiento de una obligación legal o contractual.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>8</a><a style={{fontWeight:'bold'}}> Seguridad:</a> La información sujeta a Tratamiento por el Responsable del Tratamiento o Encargado del Tratamiento a que se refiere la Ley 1581 de 2012 y sus Decretos Reglamentarios 1377 de 2013 y 886 de 2014; se deberá manejar con las medidas técnicas, humanas y administrativas que sean necesarias para otorgar seguridad a los registros evitando su adulteración, pérdida, consulta, uso o acceso no autorizado o fraudulento;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>9</a><a style={{fontWeight:'bold'}}> Confidencialidad:</a>  Todas las personas que intervengan en el Tratamiento de Datos Personales que no tengan la naturaleza de públicos están obligadas a garantizar la reserva de la información, inclusive después de finalizada su relación con alguna de las labores que comprende el Tratamiento, pudiendo sólo realizar suministro o comunicación de Datos Personales cuando ello corresponda al desarrollo de las actividades autorizadas en la Ley. A la terminación de dicho vínculo, los Datos Personales deben continuar siendo Tratados de conformidad con esta Política y con la Ley.</p>
            <p style={{paddingLeft:'3em',}}><a style={{fontWeight:'bold'}}> CAPÍTULO II. AUTORIZACIÓN Y AVISO DE PRIVACIDAD.</a> </p>
            <p style={{paddingLeft:'4em',}}><a>CUARTA. Autorización para el Tratamiento.</a> En cumplimiento de sus obligaciones legales, WENJAN deberá exigir al Titular de los Datos Personales Autorización previa, expresa e informada para ejercer Tratamiento sobre los Datos Personales a suministrar. La Autorización por parte del Titular podrá ser obtenida por WENJAN a través de cualquier medio, siempre que el mismo pueda ser objeto de consulta y verificación posterior del otorgamiento de dicha Autorización tanto por parte del Titular, como de las entidades competentes.</p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO.</a>Para el caso particular de los usuarios de las aplicaciones operadas por WENJAN, y sin perjuicio de lo establecido en la presente cláusula, la Autorización para el Tratamiento de sus Datos Personales será otorgada a través de la modalidad de “actos inequívocos”, a través del suministro voluntario de la información solicitada en el “Formulario de registro” dispuesto por WENJAN en las aplicaciones de las que es operador. </p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>QUINTA. Mecanismos para el otorgamiento de la Autorización.</a>WENJAN establece que el Titular podrá manifestar su Autorización para el Tratamiento de sus Datos Personales a través de cualquiera de los siguientes mecanismos:</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1</a>Mediante documento físico, electrónico o cualquier otro formato;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2</a>Mediante cualquier mecanismo técnico o tecnológico idóneo que permita garantizar su posterior consulta;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3</a>Mediante actos inequívocos (por ejemplo a través del suministro voluntario de la información solicitada en el “Formulario de registro” dispuesto por WENJAN en las aplicaciones de las que es operador).</p>

            <p style={{paddingLeft:'4em',}}>En todo caso, la Autorización puede constar en un documento físico, electrónico o en cualquier otro formato que permita garantizar su posterior consulta, y mediante el cual se pueda concluir de manera inequívoca, que el Titular ha otorgado su consentimiento previo, expreso e informado para que WENJAN realice el Tratamiento de sus Datos Personales de acuerdo con las finalidades informadas por la sociedad. </p>
            <p style={{paddingLeft:'4em',}}><a style={{fontWeight:'bold'}}>SEXTA. Contenido de la Autorización.</a>Dentro del marco de lo consagrado en la Ley 1581 de 2.012 y el Decreto 1377 de 2.013, la Autorización otorgada a WENJAN por el Titular de la información y Datos Personales, sin importar el medio o canal usado, debe contener lo enunciado a continuación:</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1</a> La información de contacto de WENJAN, en su calidad de Responsable del Tratamiento de los Datos Personales. Calidad adquirida en virtud del ejercicio de la recopilación de los Datos Personales del Titular;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2</a> La descripción de la naturaleza y carácter de los Datos Personales recopilados por WENJAN en su calidad de Responsable del Tratamiento;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3</a> La (s) finalidad (es) del Tratamiento de los Datos Personales solicitados por parte de WENJAN;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>4</a> Los canales y medios con los que cuenta el Titular de los Datos Personales para el ejercicio de su derecho de Habeas Data en relación con el acceso, corrección, actualización o supresión de los Datos Personales suministrados a WENJAN.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO.</a> En el evento en que los datos recolectados, sean Datos Personales de naturaleza sensible, WENJAN en su calidad de Responsable, deberá informar al Titular en el documento mediante el cual solicita la Autorización para ejercer el Tratamiento de los mismos, que no se encuentra obligado a otorgarla en ocasión del carácter sensible de éstos. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>SÉPTIMA. Aviso de privacidad</a>  Al momento de recolectar la información y los Datos Personales del Titular, WENJAN deberá notificarle por cualquier medio (ya sea mediante documento físico, electrónico o en cualquier otro formato) del Aviso de privacidad, mediante el cual le informa: </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1</a> Respecto a la existencia de las presentes políticas de Tratamiento y protección en materia de Datos Personales, las cuales serán aplicables una vez el otorgue su consentimiento previo, expreso e informado para que WENJAN realice el Tratamiento de sus datos e información de carácter personal;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2</a> La información de contacto de WENJAN, en su calidad de Responsable del Tratamiento de los Datos Personales. Calidad adquirida en virtud del ejercicio de la recopilación de los Datos Personales del Titular;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3</a> El tipo de Tratamiento al cual serán sometidos los datos y las finalidades del mismo;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>4</a> Los canales y medios con los que cuenta el Titular de los Datos Personales, ya sea de forma física o electrónica, para consultar las políticas de Tratamiento y protección en materia de Datos Personales;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>5</a> Los derechos que le asisten al Titular en ejercicio de su derecho de Habeas Data en relación con el acceso, corrección, actualización o supresión de los Datos Personales suministrados a WENJAN;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>6</a> En el evento en que WENJAN solicite el suministro de Datos Personales de naturaleza sensible, deberá informar al Titular en el aviso de privacidad, el carácter facultativo de la respuesta a las preguntas que versen sobre este tipo de datos.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO PRIMERO</a> Para el caso particular de los usuarios de las aplicaciones operadas por WENJAN, y sin perjuicio de lo establecido en la presente cláusula, el aviso de privacidad estará incluido en la cláusula de los “Términos y condiciones de uso” que regula la “Autorización para el Tratamiento de Datos Personales”.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO SEGUNDO. WENJAN</a> deberá conservar el modelo del aviso de privacidad que haya trasmitido al Titular de los Datos Personales recolectados, siempre que se siga efectuando el Tratamiento sobre los mismos, y por consiguiente, perduren las obligaciones que de éste se deriven. Por lo tanto, WENJAN se encuentra facultado para emplear medios físicos, electrónicos, informático para almacenar dicho aviso.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>OCTAVA. Tratamiento de datos sensibles. </a>  El Tratamiento de los datos sensibles a que se refiere el artículo 5° de la Ley 1581 de 2012 está prohibido, a excepción de los siguientes casos expresamente señalados en el artículo 6° de la citada norma:</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1. </a> El Titular haya dado su Autorización explícita a dicho Tratamiento, salvo en los casos que por ley no sea requerido el otorgamiento de dicha Autorización;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2. </a> El Tratamiento sea necesario para salvaguardar el interés vital del Titular y este se encuentre física o jurídicamente incapacitado. En estos eventos, los representantes legales deberán otorgar su Autorización;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3.</a> El Tratamiento sea efectuado en el curso de las actividades legítimas y con las debidas garantías por parte de una fundación, ONG, asociación o cualquier otro organismo sin ánimo de lucro, cuya finalidad sea política, filosófica, religiosa o sindical, siempre que se refieran exclusivamente a sus miembros o a las personas que mantengan contactos regulares por razón de su finalidad. En estos eventos, los datos no se podrán suministrar a terceros sin la Autorización del Titular;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>4.</a> El Tratamiento se refiera a datos que sean necesarios para el reconocimiento, ejercicio o defensa de un derecho en un proceso judicial;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>5.</a> El Tratamiento tenga una finalidad histórica, estadística o científica. En este evento deberán adoptarse las medidas conducentes a la supresión de identidad de los Titulares.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>6.</a> En el Tratamiento de Datos Personales sensibles, cuando dicho Tratamiento sea posible conforme a lo establecido en el artículo 6° de la Ley 1581 de 2012, deberán cumplirse las siguientes obligaciones: i) Informar al Titular que por tratarse de datos sensibles no está obligado a autorizar su Tratamiento. ii) Informar al Titular de forma explícita y previa, además de los requisitos generales de la Autorización para la recolección de cualquier tipo de dato personal, cuáles de los datos que serán objeto de Tratamiento son sensibles y la finalidad del Tratamiento, así como obtener su consentimiento expreso</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>7.</a> Ninguna actividad podrá condicionarse a que el Titular suministre Datos Personales sensibles.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>CAPÍTULO III. OBLIGACIONES DE PARTICIPANTES DEL RÉGIMEN DE TRATAMIENTO DE DATOS PERSONALES.  </a></p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}> NOVENA. Obligaciones de WENJAN en calidad de Responsable del Tratamiento.</a> Las siguientes son las obligaciones que ostenta WENJAN en su calidad de Responsable del Tratamiento de los Datos Personales recolectados del Titular:</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1. </a> Ejercer Tratamiento sobre los Datos Personales suministrados por el Titular, únicamente de acuerdo a aquellas finalidades para las que se encuentra debidamente facultado;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2. </a> Garantizar al Titular, en todo tiempo, el pleno y efectivo ejercicio del derecho de hábeas data;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3.</a> Solicitar y conservar, en las condiciones previstas en el Régimen de Protección de Datos Personales vigente, copia de la respectiva Autorización otorgada por el Titular;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>4.</a> Informar debidamente al Titular sobre la finalidad de la recolección y los derechos que le asisten en virtud de la Autorización otorgada;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>5.</a> Conservar la información y Datos Personales bajo las condiciones de seguridad necesarias para impedir su adulteración, pérdida, consulta, uso o acceso no autorizado o fraudulento; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>6.</a> Garantizar que la información que se suministre al Encargado del Tratamiento sea veraz, completa, exacta, actualizada, comprobable y comprensible;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>7.</a> Actualizar la información, comunicando de forma oportuna al Encargado del Tratamiento, todas las novedades respecto de los datos que previamente le haya suministrado y adoptar las demás medidas necesarias para que la información suministrada a este se mantenga actualizada;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>8.</a> Rectificar la información cuando sea incorrecta y comunicar lo pertinente al Encargado del Tratamiento;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>9.</a> Exigir al Encargado del Tratamiento en todo momento, el respeto a las condiciones de seguridad y privacidad de la información del Titular;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>10.</a> Tramitar las consultas y reclamos formulados en los términos señalados en la Ley 1581 de 2012;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>11.</a> Cumplir las instrucciones y requerimientos que imparta la Superintendencia de Industria y Comercio;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>12</a> Informar a solicitud del Titular sobre el uso dado a sus datos;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>13.</a> Informar a la autoridad de protección de datos cuando se presenten violaciones a los códigos de seguridad y existan riesgos en la administración de la información del Titular;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>14.</a> Realizar el registro ante el Registro Nacional de Bases de Datos de Bases de Datos (RNBD), de acuerdo a los criterios establecidos por la Superintendencia de Industria y Comercio, de las bases de datos con información personal que haya sido suministrado por el Titular durante el ejercicio de su actividad económica principal;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>15.</a> Tramitar las consultas y los reclamos formulados por el Titular en los términos señalados en los artículos 14 y 15 de la Ley 1581 de 2012;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>16.</a> Abstenerse de circular información que esté siendo controvertida por el Titular y cuyo bloqueo haya sido ordenado por la Superintendencia de Industria y Comercio; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>17</a>Permitir el acceso a la información únicamente a las personas que pueden tener acceso a ella; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>18</a> Designar a un área que asuma la función de protección de Datos Personales, que dará trámite a las solicitudes del Titular, para el ejercicio de los derechos a que se refiere la Ley 1581 de 2012 y el Decreto 1377 de 2013.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO</a> En el evento en que el Tratamiento sea ejercido mediante un Encargado, WENJAN en su calidad de Responsable deberá garantizar que la información que se suministre al Encargado del Tratamiento sea veraz, completa, exacta, actualizada, comprobable y comprensible y previamente haya sido autorizada por el Titular para su Tratamiento. Así mismo, contará con los medios necesarios para actualizar la información suministrada al Encargado o para informar todas las novedades respecto a aquellos datos que previamente haya suministrado</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>DÉCIMA. Obligaciones de los Encargados del Tratamiento.</a> Los Encargados del Tratamiento deberán cumplir los siguientes deberes, sin perjuicio de las demás disposiciones previstas en la presente ley y en otras que rijan su actividad: </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1</a> Garantizar al Titular, en todo tiempo, el pleno y efectivo ejercicio del derecho de hábeas data;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2</a> Conservar la información bajo las condiciones de seguridad necesarias para impedir su adulteración, pérdida, consulta, uso o acceso no autorizado o fraudulento;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3</a> Realizar oportunamente la actualización, rectificación o supresión de los datos en los términos de la Ley 1581 de 2012; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>4</a> Actualizar la información reportada por los Respnsables del Tratamiento dentro de los cinco (5) días hábiles contados a partir de su recibo; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>5.</a> Tramitar las consultas y los reclamos formulados por los Titulares en los términos señalados en la Ley 1581 de 2012; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>6.</a> Adoptar un manual interno de políticas y procedimientos para garantizar el adecuado cumplimiento de la Ley 1581 de 2012 y, en especial, para la atención de consultas y reclamos por parte de los Titulares;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>7.</a> Registrar en la Base de Datos las leyendas "reclamo en trámite" en la forma en que se regula en la Ley 1581 de 2012; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>8.</a> Insertar en la Base de Datos la leyenda "información en discusión judicial" una vez notificado por parte de la autoridad competente sobre procesos judiciales relacionados con la calidad del dato personal; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>9.</a> Abstenerse de circular información que esté siendo controvertida por el Titular y cuyo bloqueo haya sido ordenado por la Superintendencia de Industria y Comercio; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>10.</a> Permitir el acceso a la información únicamente a las personas que pueden tener acceso a ella;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>11.</a> Informar a la Superintendencia de Industria y Comercio cuando se presenten violaciones a los códigos de seguridad y existan riesgos en la administración de la información de los Titulares;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>12.</a> Cumplir las instrucciones y requerimientos que imparta la Superintendencia de Industria y Comercio.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>CAPÍTULO IV. DERECHOS DE LOS TITULARES DE LA INFORMACIÓN Y DATOS PERSONALES</a></p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>DÉCIMA  PRIMERA. Derechos de los Titulares.</a> De conformidad con lo dispuesto en el artículo 8 de la Ley 1581 de 2012 y el artículo 21 y 22 del Decreto 1377 de 2013, el Titular de los Datos Personales suministrados a WENJAN, tiene los siguientes derechos: </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1.</a> Conocer, actualizar y rectificar sus Datos Personales frente a WENJAN, en su condición de Responsable del Tratamiento, respecto a datos parciales, inexactos, incompletos, fraccionados, que induzcan a error, o aquellos cuyo Tratamiento esté expresamente prohibido o no haya sido autorizado;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2.</a> Solicitar prueba de la Autorización otorgada a WENJAN, en su condición de Responsable del Tratamiento, salvo cuando expresamente se exceptúe como requisito para el Tratamiento;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3.</a> Ser informado por WENJAN, previa solicitud, respecto del uso que le ha dado a sus Datos Personales;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>4.</a> Presentar ante la Superintendencia de Industria y Comercio quejas por infracciones a lo dispuesto en la Ley 1581 de 2012 y las demás normas que la modifiquen, adicionen o complementen, una vez haya agotado el trámite de consulta o reclamo ante el Responsable del Tratamiento;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>5</a> Revocar la Autorización y/o solicitar la supresión del dato cuando en el Tratamiento no se respeten los principios, derechos y garantías constitucionales y legales;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>6</a> Acceder en forma gratuita a sus Datos Personales que hayan sido objeto de Tratamiento;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>7</a> Tener acceso a medios de contacto otorgados por WENAJN para ejercer sus derechos y dar aplicación a los procedimientos previstos en la legislación colombiana respecto al Derecho de Habeas Data; </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>8</a> Conocer la política de Tratamiento de Datos Personales de WENJAN y los cambios, modificaciones y/o actualizaciones sobre el particular;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>9</a> Solicitar la supresión de Datos Personales cuando en el Tratamiento no se respeten los principios, derechos y garantías constitucionales y legales, cuando exista declaratoria administrativa por parte de la Superintendencia de Industria y Comercio de la infracción cometida por WENJAN respecto al régimen de protección de Datos Personales.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO</a>En virtud de la naturaleza sensible de los Datos Personales de niños, niñas y adolescentes, el ejercicio del derecho de Habeas Data relacionado con la rectificación, actualización o supresión de los mismos, deberá ser realizada por las personas que estén facultadas para representarlos, calidad que debe ser acreditada ante WENJAN.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>DÉCIMA SEGUNDA. Ejercicio del derecho de acceso.</a> El Titular de la información y Datos Personales está facultado para solicitar de forma gratuita a WENJAN, en su calidad de Responsable del Tratamiento de los Datos Personales, el acceder y consultar si su información personal está siendo objeto de Tratamiento. Así mismo, podrá solicitar información respecto a la finalidad u objeto del Tratamiento y las condiciones y generalidades del mismo. Por consiguiente, el Titular podrá consultar al Responsable respecto a: (i) la efectiva existencia del Tratamiento a que son sometidos sus Datos Personales; (ii) tener acceso a sus Datos Personales que están en posesión del Responsable; (iii) las circunstancias esenciales del Tratamiento, en relación con el tipo de Datos Personales tratados y todas y cada una de las finalidades que justifican el Tratamiento. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}> PARÁGRAFO. WENJAN </a> deberá en su calidad de Responsable del Tratamiento, previa acreditación del Titular o su apoderado, permitir el acceso a los datos solicitados y otorgar la información necesaria respecto a la consulta elaborada por el Titular. El acceso no tendrá un límite de plazo y deberá permitir al Titular la posibilidad de actualizarlos en línea, en caso que proceda alguna corrección o actualización.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>DÉCIMA TERCERA. Ejercicio del derecho de consulta.</a> En virtud de lo establecido en el artículo 14 de la Ley 1581 de 2012 y el artículo 21 del Decreto 1377 de 2013, e Titular podrá consultar a WENJAN respecto a la información de carácter personal que reposa en sus bases de datos. WENJAN deberá otorgar toda la información contenida en sus bases de datos y que esté vinculada con la identificación del Titular que realiza la consulta por cualquier de los medios o canales otorgados por la sociedad para tal fin. En este sentido, quien presente la consulta deberá: (i) determinar su identidad, incluyendo su nombre y datos de identificación; (ii) especificar de manera clara y expresa el motivo de la petición; (iii) acreditar el interés legítimo con el que actúa, adjuntando, en todo caso, los debidos soportes; (iv) indicar la dirección física o electrónica de correspondencia a la que se autorice remitir la respuesta de la petición.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO</a> Toda consulta realizada por el Titular de los datos e información personal deberá ser resuelta por WENJAN en un término máximo de diez (10) días hábiles contados a partir de la fecha de recepción de la misma. En el evento en que WENJAN no pueda resolver una consulta dentro de dicho termino, deberá informar al solicitante por escrito antes del vencimiento del término de diez (10) días los motivos por los cuales no puede resolverla y deberá señalar la fecha en la cual se atenderá formalmente cada uno de los puntos de la solicitud. Fecha que en ningún caso podrá superar los cinco (5) días hábiles siguientes al vencimiento del primer plazo</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>DÉCIMA CUARTA. Ejercicio del derecho a reclamos</a> En el evento en que el Titular de la información considere que los Datos Personales contenidos en las bases de datos de WENJAN deban ser objeto de corrección, actualización o supresión, o cuando advierta el presunto incumplimiento de cualquiera de los deberes contenidos en la Ley 1581 de 2012 y el Decreto 1377 de 2013 o cualquier otra norma aplicable. En este sentido, quien presente el reclamo deberá: (i) determinar su identidad, incluyendo su nombre y datos de identificación; (ii) especificar de manera clara y expresa el motivo del reclamo; (iii) acreditar el interés legítimo con el que actúa, adjuntando, en todo caso, los debidos soportes; (iv) indicar la dirección física o electrónica de correspondencia a la que se autorice remitir la respuesta del reclamo.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO PRIMERO</a> Todo reclamo realizado por el Titular de los datos e información personal deberá ser resuelta por WENJAN en un término máximo de quince (15) días hábiles contados a partir de la fecha de recepción del mismo. En el evento en que WENJAN no pueda resolver el reclamo dentro de dicho termino, deberá informar al solicitante por escrito antes del vencimiento del término de quince (15) días los motivos por los cuales no puede resolverlo y deberá señalar la fecha en la cual se atenderá formalmente cada uno de los puntos del reclamo. Fecha que en ningún caso podrá superar los ocho (8) días hábiles siguientes al vencimiento del primer plazo. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO SEGUNDO. </a>  En el evento en que el reclamo se encuentre incompleto, WENJAN requerirá al reclamante dentro de los cinco (5) días siguientes a la recepción del mismo, con el fin de que subsane las fallas. Transcurridos dos (2) meses desde la fecha del requerimiento, sin que el reclamante presente la información requerida, se entenderá que ha desistido del reclamo. En el evento en que WENJAN no sea competente para resolver la petición, queja o reclamo, dará traslado a quien corresponda, en un término máximo de dos (2) días hábiles, e informará de la situación al interesado. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>DÉCIMA QUINTA. Ejercicio del derecho de supresión.</a>  En el evento en que el Titular requiera la supresión o eliminación total o parcial de la información personal contenida en las bases de datos de WENJAN, en el evento en que la misma no sea necesaria o pertinente para la finalidad para la cual fueron recabados o se haya superado el periodo necesario para el cumplimiento de los fines para los que fueron solicitados. Si la supresión es procedente, la sociedad deberá realizar operativamente la supresión de tal manera que la eliminación no permita la recuperación de la información. Sin embargo, dicha solicitud podrá ser negada por WENJAN, quien en su calidad de Responsable, puede negar el ejercicio del mismo cuando: </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1.</a>  En el evento en que el Titular requiera la supresión o eliminación total o parcial de la información personal contenida en las bases de datos de WENJAN, en el evento en que la misma no sea necesaria o pertinente para la finalidad para la cual fueron recabados o se haya superado el periodo necesario para el cumplimiento de los fines para los que fueron solicitados. Si la supresión es procedente, la sociedad deberá realizar operativamente la supresión de tal manera que la eliminación no permita la recuperación de la información. Sin embargo, dicha solicitud podrá ser negada por WENJAN, quien en su calidad de Responsable, puede negar el ejercicio del mismo cuando: </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2.</a> La eliminación de datos obstaculice actuaciones judiciales o administrativas vinculadas a obligaciones fiscales, la investigación y persecución de delitos o la actualización de sanciones administrativas;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3.</a> Los datos sean necesarios para proteger los intereses jurídicamente tutelados del Titular; para realizar una acción en función del interés público, o para cumplir con una obligación legalmente adquirida por el Titular. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO</a> Si vencido el término legal respectivo, el Responsable y/o el Encargado, según fuera el caso, no hubieran eliminado los Datos Personales, el Titular tendrá derecho a solicitar a la Superintendencia de Industria y Comercio que ordene la revocatoria de la Autorización y/o la supresión de los Datos Personales. Para estos efectos se aplicará el procedimiento descrito en el artículo 22 de la Ley 1581 de 2012.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>DÉCIMA SEXTA. Revocatoria de la Autorización</a> Los Titulares de los Datos Personales pueden revocar el consentimiento al Tratamiento de sus Datos Personales en cualquier momento, siempre y cuando no lo impida una disposición legal o contractual. WENJAN deberá establecer mecanismos sencillos, de fácil acceso y gratuitos que permitan al Titular revocar su consentimiento. La revocatoria total de la Autorización podrá ser solicitada cuando las finalidades consentidas por el Titular para el Tratamiento de la información no corresponden a lo efectuado por WENJAN, por lo cual la sociedad debe dejar de tratar por completo los datos del Titular. La revocatoria parcial de la Autorización procede cuando uno de los fines enunciados por WENJAN no procede, sin embargo, otros de los informados se mantienen. Por lo cual previa Autorización otorgada por el Titular, WENJAN únicamente procederá con el Tratamiento respecto a los fines que siguen vigentes, dejándose expreso cuales son los Tratamientos que ya no son autorizados. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>DÉCIMA SÉPTIMA. Medios y canales para el ejercicio del Habeas Data.</a> En cumplimiento de lo dispuesto en el régimen de protección de Datos Personales, WENJAN dispone de un área Responsable de recibir, procesar y resolver las peticiones de Titulares de información personal o de quienes legitimen interés para lo pertinente. Los peticionarios podrán presentar sus consultas y reclamos al correo electrónico info@confirmapp.com. Adicionalmente WENJAN establece que podrá establecer los siguientes canales y medios al Titular de la información o Datos Personales para el ejercicio del Habeas Data: (i) Medios de comunicación electrónica u otros que considere pertinentes; (ii) Formularios, sistemas y otros métodos simplificados; (iii) Servicios de atención al cliente o de reclamación en sus instalaciones físicas o en su domicilio social principal.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>CAPÍTULO V. DEL TRATAMIENTO.</a></p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>DÉCIMA OCTAVA. Finalidades del Tratamiento de Datos Personales</a> Dentro del marco de lo dispuesto en los artículos 4 y 12 de la Ley 1581 de 2.012, y en cumplimiento del deber de información que ostenta WENJAN respecto de los Titulares de Datos Personales, WENJAN establece que las finalidades que se exponen a continuación, aplican, junto con los acuerdos de privacidad y confidencialidad que de manera particular se suscriban en cada caso, respecto a todos aquellos Datos Personales que WENJAN recopila mediante las aplicaciones móviles que opera, a través de sus servicios online, y por medio de otras interacciones y comunicaciones que usuarios realizan con la sociedad. En consecuencia, los Datos Personales suministrados a WENJAN por personas naturales en calidad de Titulares, serán objeto de Tratamiento conforme las siguientes finalidades de carácter general:</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>1</a> Consultar, comparar, analizar, procesar, evaluar, tratar o comparar toda la información que sobre los accionistas se encuentre almacenada en las bases de datos;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>2</a> Informar al Titular sobre cualquier situación relevante relacionada con su calidad de accionista;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>3</a> Enviar convocatorias para las reuniones ordinarias y extraordinarias de la Asamblea General de Accionistas;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>4</a> Llevar a cabo anotaciones u operaciones relacionadas con la calidad de accionista;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>5</a> Atender labores de servicio y atención al accionista;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>6</a> Dar cumplimiento a cualquiera de las obligaciones contraídas por la sociedad con el accionista Titular de la información;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>7</a> Prevenir, detectar y controlar cualquier actividad o información que se pueda interpretar como fraude, trato inequitativo o violación de confidencialidad;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>8</a> Emitir certificaciones relativas a la relación del Titular de los Datos Personales, con el Responsable;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>9</a> Cumplir con las obligaciones tributarias y de registros comerciales, corporativos y contables Del Responsable, de acuerdo a las disposiciones legales vigentes;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>10</a> Enviar los Datos Personales por medio seguro a servidores ubicados en Colombia o en el exterior, con el fin de conservar copias de seguridad o respaldos de la misma, incluso en el evento en que el Responsable contrate estos servicios con plataformas basadas en tecnología en la nube;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>11</a> Transmitir o transferir los Datos Personales a terceros ubicados en Colombia y/o en el extranjero, incluso en países que no proporcionen medidas adecuadas de protección de Datos Personales, siempre que con éstos se suscriban contratos para efectuar el Tratamiento de Datos Personales, con fines administrativos y/u operativos;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>12</a> Aplicar procedimientos de archivo, protección y custodia de los Datos Personales;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>13</a> Informar sobre las modificaciones a las Políticas de manejo de Datos Personales, así como la solicitud de nuevas autorizaciones para el Tratamiento de los Datos Personales;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>14</a> Registrar la Base de Datos en la cual se le de Tratamiento a la información ante la Superintendencia de Industria y Comercio, en los términos establecidos en la Ley 1255 de 2012 y el Decreto 886 de 2014;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>15</a>  Las demás finalidades que determine el Responsable en los procesos de obtención de Datos Personales para su Tratamiento, con el fin de dar cumplimiento a las obligaciones legales y regulatorias, así como a sus políticas de protección de Datos Personales;</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>16</a> Las demás finalidades que resulten necesarias u aconsejables que se deriven del desarrollo normal de la relación con el accionista.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>CAPÍTULO VI. MECANISMOS DE SEGURIDAD DE LA INFORMACIÓN Y DATOS PERSONALES.</a> </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>VIGÉSIMA TERCERA. Medidas de seguridad.</a> En ocasión de lo consagrado en la Ley 1581 de 2012 respecto al principio de seguridad, WENJAN adoptará las medidas necesarias de carácter técnico, humanas y administrativas, mediante las cuales garanticen la seguridad y el carácter privado de los Datos Personales recolectados en sus bases de datos, evitando su adulteración, pérdida, consulta, uso o acceso no autorizado o fraudulento. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>VIGÉSIMA CUARTA. Implementación de las medidas de seguridad.</a> WENJAN garantiza a los Titulares de los Datos Personales recopilados en sus bases de datos que mantienen protocolos de seguridad de obligatorio cumplimiento por el personal que tiene acceso a los datos de carácter personal y sistemas de información. Para lo cual, ejecuta capacitaciones al personal que ingresa a la sociedad respecto a: i). la Política de Tratamiento y Protección en materia de Datos Personales, ii): ámbito de aplicación del procedimiento con especificación detallada de los recursos protegidos y iii). Las medidas, normas, procedimientos, reglas y estándares encaminados a garantizar el nivel de seguridad exigido en la Ley 1581 de 2012 y el Decreto 1377 de 2013, y realiza controles periódicos que se deban realizar para verificar el cumplimiento de lo dispuesto en el procedimiento de seguridad que se implemente.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>CAPÍTULO VII. TRANSMISIÓN INTERNACIONAL DE DATOS E INFORMACIÓN PERSONAL</a></p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>VIGÉSIMA QUINTA. Utilización y transferencia internacional de Datos Personales.</a> De acuerdo a lo dispuesto en la Ley 1581 de 2012 y el Decreto 1377 de 2013, WENJAN podrá transferir la totalidad de los datos contenidos en las bases de datos al exterior, siempre que esté sujeto a los requerimientos legales aplicables. Por consiguiente, el Titular con la aceptación de la presente política, autoriza expresamente para transferir Información Personal al exterior, para todas las relaciones que requiera establecer WENJAN, sin perjuicio de la obligación de observar y mantener la confidencialidad de la información. Por consiguiente, WENJAN tomará las medidas necesarias para que esos terceros conozcan y se comprometan a observar las disposiciones establecidas en la presente Política, bajo el entendido de que la información personal y Datos Personales que reciban, únicamente podrá ser utilizada para asuntos directamente relacionados con las finalidades autorizadas por el Titular a WENJAN. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO</a> La sociedad también puede intercambiar personal con autoridades gubernamentales o públicas de otro tipo (incluidas, entre otras autoridades judiciales o administrativas, autoridades fiscales y organismos de investigación penal, civil, administrativa, disciplinaria y fiscal), y terceros participantes en procedimientos legales civiles y sus contadores, auditores, abogados y otros asesores y representantes, en cumplimiento de lo dispuesto en las leyes vigentes.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>CAPÍTULO VIII. CONSIDERACIONES FINALES</a></p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>VIGÉSIMA SEXTA. Modificaciones en la Política de Privacidad.</a>WENJAN podrá, cuando lo considere conveniente, cambiar los términos de sus políticas de privacidad y Tratamiento en materia de Datos Personales, sin perjuicio de las garantías dispuestas en el régimen colombiano de protección de Datos Personales. Para el efecto, realizará la publicación de un aviso en la página de internet, en la aplicación o en el mecanismo habilitado por WENJAN con quince (15) días hábiles de antelación a su implementación y durante la vigencia de la política. Los cambios sustanciales efectuados entrarán en vigor treinta (30) días después de que éstos hayan sido publicados en la plataforma o en la página web principal de la sociedad. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>PARÁGRAFO</a>En caso de no estar de acuerdo con las nuevas políticas de manejo de la información personal, los Titulares de la información o sus representantes podrán solicitar el retiro de su información, a través del canal de comunicación dispuesto para tal fin. Sin embargo, no se podrá solicitar el retiro de los datos mientras se mantenga un vínculo de cualquier orden con la sociedad.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>VIGÉSIMA SÉPTIMA. Delegado para la protección de Datos Personales. </a>  WENJAN ha dispuesto al administrador del siguiente correo electrónico: info@confirmapp.com como Encargado del manejo de los Datos Personales y de la atención de los clientes y usuarios, relacionada con la protección de los datos. Esta persona es Responsable de la recepción y atención de peticiones quejas y reclamos de conformidad con la presente política. Los datos de contacto son: (i) dirección: carrera 57 No. 79-118 en Barranquilla; (ii) teléfono de contacto: +(57) 5 3553435. El Titular de los Datos Personales podrá hacer valer sus derechos a través del correo electrónico info@confirmapp.com. Los Datos Personales que sean recolectados, almacenados, utilizados o transmitidos, permanecerán en la Base de Datos de WENJAN, teniendo en cuenta el criterio de temporalidad que sea necesario para las finalidades mencionadas en la presente política, para las cuales fueron recolectados. </p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>VIGÉSIMA OCTAVA. Medios y canales para el ejercicio del Habeas Data.</a> En cumplimiento de lo dispuesto en el régimen de protección de Datos Personales, WENJAN dispone de un área Responsable de recibir, procesar y resolver las peticiones de Titulares de información personal o de quienes legitimen interés para lo pertinente. Los peticionarios podrán presentar sus consultas y reclamos al correo electrónico info@confirmapp.com. Adicionalmente WENJAN establece que podrá establecer los siguientes canales y medios al Titular de la información o Datos Personales para el ejercicio del Habeas Data: (i) Medios de comunicación electrónica u otros que considere pertinentes; (ii) Formularios, sistemas y otros métodos simplificados; (iii) Servicios de atención al cliente o de reclamación en sus instalaciones físicas o en su domicilio social principal.</p>
            <p style={{paddingLeft:'5em',}}><a style={{fontWeight:'bold'}}>VIGÉSIMA NOVENA. Vigencia</a>Las presentes POLÍTICAS DE TRATAMIENTO Y PROTECCIÓN EN MATERIA DE DATOS PERSONALES rigen a partir de su publicación. </p>
       


            <br/>
        </div>
        <div style={{height:150, backgroundColor:'blueviolet'}}>

            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
        </div>
        </div>
    )
}
